terminal:
  font: Consolig
  shell: default
  profile: fish-prompt
  frontend: xterm
  autoOpen: false
  fontSize: 15
  fallbackFont: Ubuntu
  linePadding: 0
  bell: audible
  bracketedPaste: true
  background: colorScheme
  ligatures: true
  cursor: underline
  cursorBlink: true
  hideTabIndex: true
  hideCloseButton: false
  customShell: fish
  rightClick: menu
  pasteOnMiddleClick: true
  copyOnSelect: false
  scrollOnInput: true
  workingDirectory: /home/penguin98k/Sublime
  alwaysUseWorkingDirectory: false
  altIsMeta: false
  wordSeparator: ' .-:,;<>~!@#$%^&*|+=[]{}`~?"'''
  colorScheme:
    name: UserTheme
    foreground: hsl(220,30%,92%)
    background: '#191919'
    cursor: '#f34b00'
    colors:
      - '#191919'
      - '#E1D56B'
      - '#47D0EC'
      - '#ffc251'
      - '#47D0EC'
      - '#ba76e7'
      - '#FD9622'
      - '#c2c8d7'
      - '#7F7F7D'
      - '#F92472'
      - '#4EE071'
      - '#ffc251'
      - '#47D0EC'
      - '#F92472'
      - '#AC80E7'
      - '#c2c8d7'
  customColorSchemes:
    - name: UserTheme
      foreground: hsl(220,30%,92%)
      background: '#191919'
      cursor: '#f34b00'
      colors:
        - '#191919'
        - '#E1D56B'
        - '#47D0EC'
        - '#ffc251'
        - '#47D0EC'
        - '#ba76e7'
        - '#FD9622'
        - '#c2c8d7'
        - '#7F7F7D'
        - '#F92472'
        - '#4EE071'
        - '#ffc251'
        - '#47D0EC'
        - '#F92472'
        - '#AC80E7'
        - '#c2c8d7'
  environment: {}
  profiles:
    - name: Fish Shell
      shell: custom
      sessionOptions:
        command: fish
        args: []
        env: {}
        cwd: /home/penguin98k/Sublime
      color: '#58AD58'
      disableDynamicTitle: false
    - name: IPython 3.10
      shell: custom
      sessionOptions:
        command: python
        args:
          - '-m'
          - IPython
        env: {}
        cwd: /home/penguin98k/Sublime
      color: '#046FCB'
      disableDynamicTitle: true
    - name: IPython 3.9
      shell: custom
      sessionOptions:
        command: python3.9
        args:
          - '-m'
          - IPython
        env: {}
        cwd: /home/penguin98k/Sublime
      color: '#044F91'
      disableDynamicTitle: true
    - name: Jupyter Lab
      shell: custom
      sessionOptions:
        command: python3.9
        args:
          - '-m'
          - jupyterlab
        env: {}
        cwd: /home/penguin98k/Sublime
      color: '#5C3B76'
      disableDynamicTitle: true
    - name: Jupyter Notebook
      shell: custom
      sessionOptions:
        command: python3.9
        args:
          - '-m'
          - notebook
        env: {}
        cwd: /home/penguin98k/Sublime
      color: '#333A42'
      disableDynamicTitle: true
  useConPTY: true
  recoverTabs: true
  warnOnMultilinePaste: false
  showDefaultProfiles: false
  searchRegexAlwaysEnabled: false
  searchOptions:
    regex: false
    wholeWord: false
    caseSensitive: false
  detectProgress: true
  scrollbackLines: 25000
hotkeys:
  show-quick-cmds:
    - Alt-Q
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  new-tab:
    - Super-N
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  copy-current-path: []
  shell: {}
  profile: {}
  serial:
    - Alt-K
  restart-serial-session: []
  settings:
    - Ctrl-Shift-P
  ssh:
    - Ctrl-Alt-S
  restart-ssh-session: []
  new-window:
    - Ctrl-Shift-N
  toggle-window:
    - Super-`
  toggle-fullscreen:
    - F11
  close-tab:
    - Ctrl-Alt-W
  reopen-tab:
    - Ctrl-Shift-T
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Super-Shift-Right
  split-bottom:
    - Super-Shift-Down
  split-left:
    - Super-Shift-Left
  split-top:
    - Super-Shift-Up
  pane-nav-right:
    - Super-Right
  pane-nav-down:
    - Super-Down
  pane-nav-up:
    - Super-Up
  pane-nav-left:
    - Super-Left
  pane-maximize:
    - Alt-F
  close-pane:
    - Ctrl-Shift-W
serial:
  connections: []
  options: {}
ssh:
  connections: []
  recentConnections: []
  warnOnClose: false
  winSCPPath: null
pluginBlacklist: []
appearance:
  dock: bottom
  dockScreen: current
  dockFill: 0.12
  dockSpace: 1
  dockHideOnBlur: true
  dockAlwaysOnTop: true
  flexTabs: true
  tabsLocation: left
  cycleTabs: true
  theme: Standard
  frame: native
  css: '/* * { color: blue !important; } */'
  opacity: 1
  vibrancy: true
  vibrancyType: blur
enableAnalytics: true
enableWelcomeTab: false
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAutomaticUpdates: true
qc:
  cmds: []
titleControl:
  replacePattern: \t
  removePattern: penguin98k/
clickableLinks: {}
